services:

    frontend:
        image: harlon/codev-front:0.0.1
        restart: unless-stopped
        environment:
            VITE_API_URL: http://127.0.0.1:8080
        ports:
            - 5173:5173

    backend:
        image: brenoduarte655/codev-api:2.1
        restart: unless-stopped
        environment:
            DATABASE_URL: jdbc:postgresql://db:5432/codev-db
            USERNAME: postgres
            PASSWORD: postgres
        ports:
            - 8080:8080
        depends_on:
            db:
                condition: service_started

    swagger-ui:
        image: swaggerapi/swagger-ui
        container_name: swagger_ui_container
        ports:
            - 80:8080
        volumes:
            - ./doc:/usr/share/nginx/html/doc
        environment:
            API_URL: doc/openapi.yaml

    db:
        container_name: postgres
        image: postgres:14
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: codev-db
        ports:
            - 5432:5432